### Tensors

In [2]:
import numpy as np

In [11]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[4,4,4],[5,5,5],[3,3,3]])

In [12]:
mat.ndim
mat2.ndim

2

In [13]:
d3_tensor=np.array([mat,mat2])

In [15]:
print(d3_tensor)
print(d3_tensor.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 4 4]
  [5 5 5]
  [3 3 3]]]
(2, 3, 3)


In [7]:
v=np.array([1,2,3])
v.ndim

1

In [16]:
#for the pandas dataframe....df=df.iloc[row start:row end,col start:col end]